// ── Indian States ──────────────────────────────────────────────────────────────
export const INDIAN_STATES = [
  'Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh',
  'Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka',
  'Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram',
  'Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana',
  'Tripura','Uttar Pradesh','Uttarakhand','West Bengal',
  'Andaman and Nicobar Islands','Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi','Jammu and Kashmir','Ladakh','Lakshadweep','Puducherry',
];

// ── Districts by State ─────────────────────────────────────────────────────────
export const DISTRICTS_BY_STATE = {
  'Andhra Pradesh': [
    'Alluri Sitharama Raju','Anakapalli','Ananthapuramu','Annamayya',
    'Bapatla','Chittoor','East Godavari','Eluru','Guntur','Kakinada',
    'Konaseema','Krishna','Kurnool','Manyam','Nandyal','NTR','Palnadu',
    'Prakasam','Sri Potti Sriramulu Nellore','Sri Sathya Sai','Srikakulam',
    'Tirupati','Visakhapatnam','Vizianagaram','West Godavari','YSR Kadapa',
  ],
  'Arunachal Pradesh': [
    'Anjaw','Capital Complex Itanagar','Changlang','Dibang Valley',
    'East Kameng','East Siang','Kamle','Kra Daadi','Kurung Kumey','Lepa Rada',
    'Lohit','Longding','Lower Dibang Valley','Lower Siang','Lower Subansiri',
    'Namsai','Pakke Kessang','Papum Pare','Shi Yomi','Siang','Tawang','Tirap',
    'Upper Siang','Upper Subansiri','West Kameng','West Siang',
  ],
  'Assam': [
    'Bajali','Baksa','Barpeta','Biswanath','Bongaigaon','Cachar','Charaideo',
    'Chirang','Darrang','Dhemaji','Dhubri','Dibrugarh','Dima Hasao','Goalpara',
    'Golaghat','Hailakandi','Hojai','Jorhat','Kamrup','Kamrup Metropolitan',
    'Karbi Anglong','Karimganj','Kokrajhar','Lakhimpur','Majuli','Morigaon',
    'Nagaon','Nalbari','Sivasagar','Sonitpur','South Salmara-Mankachar',
    'Tamulpur','Tinsukia','Udalguri','West Karbi Anglong',
  ],
  'Bihar': [
    'Araria','Arwal','Aurangabad','Banka','Begusarai','Bhagalpur','Bhojpur',
    'Buxar','Darbhanga','East Champaran','Gaya','Gopalganj','Jamui','Jehanabad',
    'Kaimur','Katihar','Khagaria','Kishanganj','Lakhisarai','Madhepura',
    'Madhubani','Munger','Muzaffarpur','Nalanda','Nawada','Patna','Purnia',
    'Rohtas','Saharsa','Samastipur','Saran','Sheikhpura','Sheohar','Sitamarhi',
    'Siwan','Supaul','Vaishali','West Champaran',
  ],
  'Chhattisgarh': [
    'Balod','Baloda Bazar','Balrampur','Bastar','Bemetara','Bijapur','Bilaspur',
    'Dantewada','Dhamtari','Durg','Gariaband','Gaurela-Pendra-Marwahi',
    'Janjgir-Champa','Jashpur','Kabirdham','Kanker','Khairagarh','Kondagaon',
    'Korba','Koriya','Mahasamund','Manendragarh','Mohla-Manpur','Mungeli',
    'Narayanpur','Raigarh','Raipur','Rajnandgaon','Sakti',
    'Sarangarh-Bilaigarh','Sukma','Surajpur','Surguja',
  ],
  'Goa': ['North Goa','South Goa'],
  'Gujarat': [
    'Ahmedabad','Amreli','Anand','Aravalli','Banaskantha','Bharuch','Bhavnagar',
    'Botad','Chhota Udaipur','Dahod','Dang','Devbhoomi Dwarka','Gandhinagar',
    'Gir Somnath','Jamnagar','Junagadh','Kheda','Kutch','Mahisagar','Mehsana',
    'Morbi','Narmada','Navsari','Panchmahal','Patan','Porbandar','Rajkot',
    'Sabarkantha','Surat','Surendranagar','Tapi','Vadodara','Valsad',
  ],
  'Haryana': [
    'Ambala','Bhiwani','Charkhi Dadri','Faridabad','Fatehabad','Gurugram',
    'Hisar','Jhajjar','Jind','Kaithal','Karnal','Kurukshetra','Mahendragarh',
    'Nuh','Palwal','Panchkula','Panipat','Rewari','Rohtak','Sirsa','Sonipat',
    'Yamunanagar',
  ],
  'Himachal Pradesh': [
    'Bilaspur','Chamba','Hamirpur','Kangra','Kinnaur','Kullu',
    'Lahaul and Spiti','Mandi','Shimla','Sirmaur','Solan','Una',
  ],
  'Jharkhand': [
    'Bokaro','Chatra','Deoghar','Dhanbad','Dumka','East Singhbhum','Garhwa',
    'Giridih','Godda','Gumla','Hazaribagh','Jamtara','Khunti','Koderma',
    'Latehar','Lohardaga','Pakur','Palamu','Ramgarh','Ranchi','Sahibganj',
    'Seraikela Kharsawan','Simdega','West Singhbhum',
  ],
  'Karnataka': [
    'Bagalkot','Ballari','Belagavi','Bengaluru Rural','Bengaluru Urban','Bidar',
    'Chamarajanagar','Chikballapur','Chikkamagaluru','Chitradurga',
    'Dakshina Kannada','Davanagere','Dharwad','Gadag','Hassan','Haveri',
    'Kalaburagi','Kodagu','Kolar','Koppal','Mandya','Mysuru','Raichur',
    'Ramanagara','Shivamogga','Tumakuru','Udupi','Uttara Kannada',
    'Vijayanagara','Vijayapura','Yadgir',
  ],
  'Kerala': [
    'Alappuzha','Ernakulam','Idukki','Kannur','Kasaragod','Kollam','Kottayam',
    'Kozhikode','Malappuram','Palakkad','Pathanamthitta','Thiruvananthapuram',
    'Thrissur','Wayanad',
  ],
  'Madhya Pradesh': [
    'Agar Malwa','Alirajpur','Anuppur','Ashoknagar','Balaghat','Barwani',
    'Betul','Bhind','Bhopal','Burhanpur','Chhatarpur','Chhindwara','Damoh',
    'Datia','Dewas','Dhar','Dindori','Guna','Gwalior','Harda','Hoshangabad',
    'Indore','Jabalpur','Jhabua','Katni','Khandwa','Khargone','Maihar',
    'Mandla','Mandsaur','Morena','Narsinghpur','Neemuch','Niwari','Panna',
    'Raisen','Rajgarh','Ratlam','Rewa','Sagar','Satna','Sehore','Seoni',
    'Shahdol','Shajapur','Sheopur','Shivpuri','Sidhi','Singrauli','Tikamgarh',
    'Ujjain','Umaria','Vidisha',
  ],
  'Maharashtra': [
    'Ahmednagar','Akola','Amravati','Aurangabad','Beed','Bhandara','Buldhana',
    'Chandrapur','Dhule','Gadchiroli','Gondia','Hingoli','Jalgaon','Jalna',
    'Kolhapur','Latur','Mumbai City','Mumbai Suburban','Nagpur','Nanded',
    'Nandurbar','Nashik','Osmanabad','Palghar','Parbhani','Pune','Raigad',
    'Ratnagiri','Sangli','Satara','Sindhudurg','Solapur','Thane','Wardha',
    'Washim','Yavatmal',
  ],
  'Manipur': [
    'Bishnupur','Chandel','Churachandpur','Imphal East','Imphal West',
    'Jiribam','Kakching','Kamjong','Kangpokpi','Noney','Pherzawl','Senapati',
    'Tamenglong','Tengnoupal','Thoubal','Ukhrul',
  ],
  'Meghalaya': [
    'East Garo Hills','East Jaintia Hills','East Khasi Hills',
    'Eastern West Khasi Hills','North Garo Hills','Ri Bhoi','South Garo Hills',
    'South West Garo Hills','South West Khasi Hills','West Garo Hills',
    'West Jaintia Hills','West Khasi Hills',
  ],
  'Mizoram': [
    'Aizawl','Champhai','Hnahthial','Khawzawl','Kolasib','Lawngtlai',
    'Lunglei','Mamit','Saiha','Saitual','Serchhip',
  ],
  'Nagaland': [
    'Chumoukedima','Dimapur','Kiphire','Kohima','Longleng','Mokokchung','Mon',
    'Niuland','Noklak','Peren','Phek','Shamator','Tseminyü','Tuensang',
    'Wokha','Zunheboto',
  ],
  'Odisha': [
    'Angul','Balangir','Balasore','Bargarh','Bhadrak','Boudh','Cuttack',
    'Deogarh','Dhenkanal','Gajapati','Ganjam','Jagatsinghpur','Jajpur',
    'Jharsuguda','Kalahandi','Kandhamal','Kendrapara','Kendujhar','Khordha',
    'Koraput','Malkangiri','Mayurbhanj','Nabarangpur','Nayagarh','Nuapada',
    'Puri','Rayagada','Sambalpur','Subarnapur','Sundargarh',
  ],
  'Punjab': [
    'Amritsar','Barnala','Bathinda','Faridkot','Fatehgarh Sahib','Fazilka',
    'Ferozepur','Gurdaspur','Hoshiarpur','Jalandhar','Kapurthala','Ludhiana',
    'Malerkotla','Mansa','Moga','Mohali','Muktsar','Pathankot','Patiala',
    'Rupnagar','Sangrur','Shahid Bhagat Singh Nagar','Tarn Taran',
  ],
  'Rajasthan': [
    'Ajmer','Alwar','Anupgarh','Balotra','Banswara','Baran','Barmer','Beawar',
    'Bharatpur','Bhilwara','Bikaner','Bundi','Chittorgarh','Churu','Dausa',
    'Deeg','Dholpur','Didwana-Kuchaman','Dudu','Dungarpur','Ganganagar',
    'Gangapur City','Hanumangarh','Jaipur','Jaipur Rural','Jaisalmer','Jalore',
    'Jhalawar','Jhunjhunu','Jodhpur','Jodhpur Rural','Karauli','Kekri',
    'Khairthal-Tijara','Kotputli-Behror','Kota','Nagaur','Neem Ka Thana',
    'Pali','Phalodi','Pratapgarh','Rajsamand','Salumbar','Sanchore',
    'Sawai Madhopur','Shahpura','Sikar','Sirohi','Sri Ganganagar','Tonk',
    'Udaipur',
  ],
  'Sikkim': [
    'East Sikkim','North Sikkim','Pakyong','Soreng','South Sikkim','West Sikkim',
  ],
  'Tamil Nadu': [
    'Ariyalur','Chengalpattu','Chennai','Coimbatore','Cuddalore','Dharmapuri',
    'Dindigul','Erode','Kallakurichi','Kancheepuram','Kanyakumari','Karur',
    'Krishnagiri','Madurai','Mayiladuthurai','Nagapattinam','Namakkal',
    'Nilgiris','Perambalur','Pudukkottai','Ramanathapuram','Ranipet','Salem',
    'Sivaganga','Tenkasi','Thanjavur','Theni','Thoothukudi','Tiruchirappalli',
    'Tirunelveli','Tirupathur','Tiruppur','Tiruvallur','Tiruvannamalai',
    'Tiruvarur','Vellore','Villupuram','Virudhunagar',
  ],
  'Telangana': [
    'Adilabad','Bhadradri Kothagudem','Hanumakonda','Hyderabad','Jagtial',
    'Jangaon','Jayashankar Bhupalpally','Jogulamba Gadwal','Kamareddy',
    'Karimnagar','Khammam','Komaram Bheem Asifabad','Mahabubabad',
    'Mahabubnagar','Mancherial','Medak','Medchal-Malkajgiri','Mulugu',
    'Nagarkurnool','Nalgonda','Narayanpet','Nirmal','Nizamabad','Peddapalli',
    'Rajanna Sircilla','Rangareddy','Sangareddy','Siddipet','Suryapet',
    'Vikarabad','Wanaparthy','Warangal','Yadadri Bhuvanagiri',
  ],
  'Tripura': [
    'Dhalai','Gomati','Khowai','North Tripura','Sepahijala','Sipahijala',
    'South Tripura','Unakoti','West Tripura',
  ],
  'Uttar Pradesh': [
    'Agra','Aligarh','Ambedkar Nagar','Amethi','Amroha','Auraiya','Ayodhya',
    'Azamgarh','Baghpat','Bahraich','Ballia','Balrampur','Banda','Barabanki',
    'Bareilly','Basti','Bhadohi','Bijnor','Budaun','Bulandshahr','Chandauli',
    'Chitrakoot','Deoria','Etah','Etawah','Farrukhabad','Fatehpur','Firozabad',
    'Gautam Buddha Nagar','Ghaziabad','Ghazipur','Gonda','Gorakhpur',
    'Hamirpur','Hapur','Hardoi','Hathras','Jalaun','Jaunpur','Jhansi',
    'Kannauj','Kanpur Dehat','Kanpur Nagar','Kasganj','Kaushambi','Kushinagar',
    'Lakhimpur Kheri','Lalitpur','Lucknow','Maharajganj','Mahoba','Mainpuri',
    'Mathura','Mau','Meerut','Mirzapur','Moradabad','Muzaffarnagar','Pilibhit',
    'Pratapgarh','Prayagraj','Raebareli','Rampur','Saharanpur','Sambhal',
    'Sant Kabir Nagar','Shahjahanpur','Shamli','Shravasti','Siddharthnagar',
    'Sitapur','Sonbhadra','Sultanpur','Unnao','Varanasi',
  ],
  'Uttarakhand': [
    'Almora','Bageshwar','Chamoli','Champawat','Dehradun','Haridwar','Nainital',
    'Pauri Garhwal','Pithoragarh','Rudraprayag','Tehri Garhwal',
    'Udham Singh Nagar','Uttarkashi',
  ],
  'West Bengal': [
    'Alipurduar','Bankura','Birbhum','Cooch Behar','Dakshin Dinajpur',
    'Darjeeling','Hooghly','Howrah','Jalpaiguri','Jhargram','Kalimpong',
    'Kolkata','Malda','Murshidabad','Nadia','North 24 Parganas',
    'Paschim Bardhaman','Paschim Medinipur','Purba Bardhaman','Purba Medinipur',
    'Purulia','South 24 Parganas','Uttar Dinajpur',
  ],
  'Andaman and Nicobar Islands': [
    'Nicobar','North and Middle Andaman','South Andaman',
  ],
  'Chandigarh': ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Dadra and Nagar Haveli','Daman','Diu',
  ],
  'Delhi': [
    'Central Delhi','East Delhi','New Delhi','North Delhi','North East Delhi',
    'North West Delhi','Shahdara','South Delhi','South East Delhi',
    'South West Delhi','West Delhi',
  ],
  'Jammu and Kashmir': [
    'Anantnag','Bandipora','Baramulla','Budgam','Doda','Ganderbal','Jammu',
    'Kathua','Kishtwar','Kulgam','Kupwara','Poonch','Pulwama','Rajouri',
    'Ramban','Reasi','Samba','Shopian','Srinagar','Udhampur',
  ],
  'Ladakh': ['Kargil','Leh'],
  'Lakshadweep': ['Lakshadweep'],
  'Puducherry': ['Karaikal','Mahe','Puducherry','Yanam'],
};

// ── Approximate state centre coordinates [lat, lon] ───────────────────────────
export const STATE_COORDS = {
  'Andhra Pradesh':                              [15.9129, 79.7400],
  'Arunachal Pradesh':                           [28.2180, 94.7278],
  'Assam':                                       [26.2006, 92.9376],
  'Bihar':                                       [25.0961, 85.3131],
  'Chhattisgarh':                                [21.2787, 81.8661],
  'Goa':                                         [15.2993, 74.1240],
  'Gujarat':                                     [22.2587, 71.1924],
  'Haryana':                                     [29.0588, 76.0856],
  'Himachal Pradesh':                            [31.1048, 77.1734],
  'Jharkhand':                                   [23.6102, 85.2799],
  'Karnataka':                                   [15.3173, 75.7139],
  'Kerala':                                      [10.8505, 76.2711],
  'Madhya Pradesh':                              [22.9734, 78.6569],
  'Maharashtra':                                 [19.7515, 75.7139],
  'Manipur':                                     [24.6637, 93.9063],
  'Meghalaya':                                   [25.4670, 91.3662],
  'Mizoram':                                     [23.1645, 92.9376],
  'Nagaland':                                    [26.1584, 94.5624],
  'Odisha':                                      [20.9517, 85.0985],
  'Punjab':                                      [31.1471, 75.3412],
  'Rajasthan':                                   [27.0238, 74.2179],
  'Sikkim':                                      [27.5330, 88.5122],
  'Tamil Nadu':                                  [11.1271, 78.6569],
  'Telangana':                                   [18.1124, 79.0193],
  'Tripura':                                     [23.9408, 91.9882],
  'Uttar Pradesh':                               [26.8467, 80.9462],
  'Uttarakhand':                                 [30.0668, 79.0193],
  'West Bengal':                                 [22.9868, 87.8550],
  'Andaman and Nicobar Islands':                 [11.7401, 92.6586],
  'Chandigarh':                                  [30.7333, 76.7794],
  'Dadra and Nagar Haveli and Daman and Diu':    [20.1809, 73.0169],
  'Delhi':                                       [28.7041, 77.1025],
  'Jammu and Kashmir':                           [33.7782, 76.5762],
  'Ladakh':                                      [34.1526, 77.5770],
  'Lakshadweep':                                 [10.5667, 72.6417],
  'Puducherry':                                  [11.9416, 79.8083],
};

// ── Crop varieties ─────────────────────────────────────────────────────────────
export const CROP_VARIETIES = {
  rice:       ['Basmati','IR 64','Sona Masoori','Swarna','Pusa 44','MTU 7029','BPT 5204','Jaya','HMT','Govind','NDR 97'],
  wheat:      ['HD 2967','PBW 343','WH 542','GW 322','K 307','HD 3086','DBW 17','DBW 303','Raj 4120','UP 2382'],
  maize:      ['DHM 117','Vivek 9','HQPM 1','NK 6240','Pioneer 30V92','DKC 9081','Bioseed 9637','PAC 740'],
  cotton:     ['Bt Cotton','MCU 5','LRA 5166','Suvin','DCH 32','H 4','Bunny BG II','MRC 7017'],
  potato:     ['Kufri Jyoti','Kufri Chipsona 1','Kufri Chipsona 3','Kufri Pushkar','Kufri Bahar','Kufri Sindhuri','Kufri Khyati','Kufri Lalima'],
  tomato:     ['Pusa Ruby','Pusa Hybrid 2','Arka Vikas','CO 3','PKM 1','Arka Ahuti','Navodaya','Rashmi'],
  sugarcane:  ['Co 86032','CoJ 64','CoLk 94184','CoS 767','8001','Co 0238','CoSe 01434','CoJ 88'],
  soybean:    ['JS 335','JS 9305','MAUS 61','NRC 37','Pusa 16','JS 9560','Pratap Soya 45','RVS 2001-4'],
  groundnut:  ['TAG 24','GG 20','K 6','TG 26','JL 24','Girnar 3','GG 7','Dh 86'],
  mustard:    ['Pusa Bold','Varuna','Kranti','RH 30','Urvashi','RH 749','DRMR 150-35','Laxmi'],
  onion:      ['Nasik Red','Agrifound Dark Red','Bhima Super','Agrifound White','Bhima Kiran','Phule Samarth','N 2-4-1'],
  chickpea:   ['Kabuli Chana','Desi (Brown)','JG 11','Phule G 5','RSG 888','KPG 59','ICCC 37','BGD 72'],
  lentil:     ['Pant L 406','IPL 81','K 75','Mallika','Noori','DPL 62','Asha','WBL 77'],
  sunflower:  ['Modern','KBSH 1','DRSH 1','Morden','PAC 36','LSFH 35','Sungold','CO 4'],
  barley:     ['K 572','BH 393','DWR 28','Ratna','Dolma','NDB 1173','K 560','RD 2552'],
};
